/** @type {import('tailwindcss').Config} */
export default {
   content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
   theme: {
      extend: {
         colors: {
            "body-color": "#FFFFFA",
            "primary-color": "#6a1300",
            "secondary-color": "#dfca00",
            "tertiary-color": "#B21E02",
            "quaternary-color": "#1D8DD9",
            "quinary-color": "#0D427A",
            "senary-color": "#8D8D8D",
            "septenary-color": "#003B4F",
            "octonary-color": "#8D1802",
            "nonary-color": "#DBDBDB",
            "denary-color": "#FFFF00",
            "eleventh-color": "#1C8DD9",
            "twelfth-color": "#686961",
            "thirteenth-color": "#FFFFE6",
            "fourteenth-color": "#9A1A01 ",
            "fifteenth-color": "#48322A",
            "sixteenth-color": "#B82F15",
            "seventeenth-color": "#646461 ",
            "eighteenth-color": "#FFFFEF",
            "nineteenth-color": "#936B62",
            "twentieth-color": "#585858",
            "twenty-first-color": "#83857A",
            "twenty-second-color": "#94AAB1",
            "twenty-third-color": "#EDEDED",
            "twenty-fourth-color": "#F3DC08",
            "twenty-fifth-color": "#3498DB",
            "twenty-sixth-color": "#6A1300",
            "twenty-seventh-color": "#EFEFEF",
            "twenty-eighth-color": "#540F00",
            "twenty-ninth-color": "#E24B01",
            "thirtieth-color": "#FF6600",
            "thirty-first-color": "#0F4DD3",
            "thirty-second-color": "#430B01",
            "thirty-third-color": "#B5B5B4",
            "thirty-fourth-color": "#3096DB",
            "thirty-fifth-color": "#F6F6F6",
            "thirty-sixth-color": "#003b4f",
            "thirty-seventh-color": "#ff6600",
            "thirty-eighth-color": "#CBCBCB",
            "thirty-ninth-color": "#F9F9F9",
            "fortieth-color": "rgb(232, 240, 254)",
            "forty-first-color": "#FFFFF6",
            "forty-second-color": "#CC0000",
            "forty-third-color": "#DFCA00",
            "forty-fourth-color": "#EAEAEA",
            "forty-fifth-color": "#002F3F",
            "forty-sixth-color": "#3E0B00",
            "forty-seventh-color": "#1D5161",
            "forty-eighth-color": "#30606D",
            "forty-ninth-color": "#FFFFCC",
            "fiftieth-color": "#FF7212",
            "fifty-first-color": "#D1D1D1",
            "fifty-second-color": "#FEDBD7",
            "fifty-third-color": "#FFF1F0",
            "fifty-fourth-color": "#FF0000",
            "fifty-fifth-color": "#F1F1F1",
            "fifty-sixth-color": "#3B3B3B",
            "fifty-seventh-color": "#FFC2D4",
            "fifty-eighth-color": "#EEEEEE",
            "fifty-ninth-color": "#FC1518",
            "sixtieth-color": "#430B01",
            "sixty-first-color": "rgb(0, 0, 255)",
         },
      },
   },
   plugins: [],
};
